;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="State.Equipped.HeadGeer",NewTagName="State.Equipped.HeadGear")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="State.Equipped.ChestArmor",DevComment="")
+GameplayTagList=(Tag="State.Equipped.ChestRig",DevComment="")
+GameplayTagList=(Tag="State.Equipped.Goggles",DevComment="")
+GameplayTagList=(Tag="State.Equipped.HeadGear",DevComment="")
+GameplayTagList=(Tag="State.Equipped.Headset",DevComment="")
+GameplayTagList=(Tag="State.Equipped.MainWeapon",DevComment="")
+GameplayTagList=(Tag="State.Equipped.MeleeWeapon",DevComment="")
+GameplayTagList=(Tag="State.Equipped.SubWeapon",DevComment="")

